# Generated by Django 6.1.1 on 2026-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(choices=[('MD. Minto Mia', 'MD. Minto Mia'), ('Sompa Rani', 'Sompa Rani'), ('Proxy Operator', 'Proxy Operator')], max_length=100)),
                ('transaction_type', models.CharField(choices=[('Sale', 'Card Sale'), ('Replace', 'Replace'), ('Damage', 'Damage')], max_length=20)),
                ('card_quantity', models.PositiveIntegerField(default=1)),
                ('price_per_card', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
